[package]
name = "vigilant-doodle-assets"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
publish = false

[lib]
crate-type = ["rlib"]

[dependencies]
bevy = { workspace = true }
bevy_asset_loader = { workspace = true }
vigilant-doodle-core = { path = "../core" }
