[package]
name = "vigilant-doodle-ai"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
publish = false

[lib]
crate-type = ["rlib"]

[dependencies]
bevy = { workspace = true }
vigilant-doodle-core = { path = "../core" }
vigilant-doodle-gameplay = { path = "../gameplay" }
