[package]
name = "vigilant-doodle-audio"
version = "0.2.0"
edition.workspace = true
authors.workspace = true
publish = false

[lib]
crate-type = ["rlib"]

[dependencies]
bevy = { workspace = true }
vigilant-doodle-core = { path = "../core" }
# bevy_kira_audio = { workspace = true }  # 预留：未来添加音频时启用
